# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    # Look for a `requirements` in the `root` directory
    directory: "/requirements"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for version updates only
    labels:
      - "ci"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 5
    reviewers:
      - "carmocca"
      - "Lightning-AI/teams/core-lightning"
