language: python
python:
  - "3.7"
# command to install dependencies
cache: pip
install:
  - pip install -e .
  - pip install -r requirements.txt --ignore-installed

# keep build from timing out
dist: xenial

# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below