# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - master
      - release/*
pr:
  - master
  - release/*

jobs:
  - job: pytest
    # how long to run the job before automatically cancelling
    timeoutInMinutes: 45
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: 2

    pool: dsvm-spot-pool

    #strategy:
    #  matrix:
    #    PT16:
    #      torch.version: '1.6'
    #      python.version: '3.7'

    # ToDo: this need to have installed docker in the base image...
    #container: pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.6
    #container: "pytorchlightning/pytorch_lightning:base-cuda-py$[ variables['python.version'] ]-torch1.6"
    container:
      # base ML image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
      image: "pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.6"
      #endpoint: azureContainerRegistryConnection
      options: "--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all"

    workspace:
      clean: all

    steps:

    - bash: |
        lspci | egrep 'VGA|3D'
        whereis nvidia
        nvidia-smi
        python --version
        pip --version
        pip list
      displayName: 'Image info & NVIDIA'

- script: |
    # python -m coverage run --source pytorch_lightning -m pytest pytorch_lightning tests -v --durations=50
    python -m coverage run --source pytorch_lightning -m pytest pytorch_lightning tests --ignore tests/plugins/test_sharded_plugin.py --ignore tests/trainer/test_dataloaders.py --ignore tests/metrics -v --durations=50
    # Todo: Find why those tests are failing when run in the main pytest.
    python -m coverage run -a --source pytorch_lightning -m pytest tests/metrics -v --durations=50
    python -m coverage run -a --source pytorch_lightning -m pytest tests/plugins/test_sharded_plugin.py tests/trainer/test_dataloaders.py -v --durations=50

  displayName: 'Testing: standard'

    - script: |
        python tests/collect_env_details.py
      displayName: 'Env details'

    - bash: |
        wget https://pl-public-data.s3.amazonaws.com/legacy/checkpoints.zip -P legacy/
        unzip -o legacy/checkpoints.zip -d legacy/
        ls -l legacy/checkpoints/
      displayName: 'Get legacy checkpoints'

    - script: |
        python -m coverage run --source pytorch_lightning -m pytest pytorch_lightning tests -v --durations=50
      displayName: 'Testing: standard'

    - script: |
        sh tests/special_tests.sh
      displayName: 'Testing: special'

    - bash: |
        python -m coverage report
        python -m coverage xml
        codecov --token $(CODECOV_TOKEN) --flags=gpu,pytest --name="GPU-coverage" --env=linux,azure
      displayName: 'Statistics'

    - script: |
        python -m pytest benchmarks pl_examples -v --maxfail=2 --durations=0
      displayName: 'Testing: extended'
