site_name: PyTorch lightning Documentation
theme:
  name: 'material'
docs_dir: docs
repo_url: https://github.com/williamFalcon/pytorch-lightning
site_dir: 'site'
site_description: 'Documentation for PyTorch LightningModule, the researcher version of keras.'

dev_addr: '0.0.0.0:8000'
#google_analytics: ['UA-aasd', 'sitename']

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
