blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url: https://lightning.ai/forums
    about: Ask and answer Lightning related questions.
  - name: ğŸ’¬ Chat with us
    url: https://discord.gg/VptPCZkGNa
    about: Live chat with experts, engineers, and users in our Discord community.
  - name: ğŸ“– Read the documentation
    url: https://lightning.ai/lightning-docs/
    about: Please consult the documentation before opening any issues!
  - name: ğŸ™‹ Contact us about professional services
    url: https://lightning.ai
    about: Contact the Lightning.ai sales team for paid support.
