blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/Lightning-AI/lightning/discussions/new
    about: Ask and answer Lightning related questions.
  - name: ğŸ’¬ Chat with us
    url: https://www.pytorchlightning.ai/community
    about: Live chat with experts, engineers, and users in our Slack community.
  - name: ğŸ“– Read the documentation
    url: https://lightning.ai/lightning-docs/
    about: Please consult the documentation before opening any issues!
  - name: ğŸ™‹ Contact us about professional services
    url: https://lightning.ai
    about: Contact the Lightning.ai sales team for paid support.
