# Pipeline to run the HPU tests in DL1 Instance

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "refs/tags/*"
pr:
  - "master"
  - "release/*"

jobs:
  - job: hpu

    # how long to run the job before automatically cancelling
    timeoutInMinutes: "5"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"

    pool: intel-hpus

    workspace:
      clean: all

    steps:
    - bash: |
        hwinfo --short
      displayName: 'Instance HW info'

    - bash: |
        pip install . --requirement requirements/test.txt
      displayName: 'Install dependencies'

    - bash: |
         python ".azure-pipelines/run_hpu_tests.py"
      displayName: 'HPU Tests in parallel'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'hpu*_test-results.xml'
        testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
      condition: succeededOrFailed()
      displayName: 'Publish test results'
