# Pipeline to run the HPU tests in DL1 Instance

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "refs/tags/*"
pr:
  - "master"
  - "release/*"

jobs:
  - job: Hpu

    # how long to run the job before automatically cancelling
    timeoutInMinutes: "5"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"

    pool: intel-hpus

    workspace:
      clean: all

    steps:

    - bash: |
        python setup.py bdist_wheel
        pip install -U ./dist/pytorch_lightning*
        pip install . --requirement requirements/hpu.txt
      displayName: 'Install dependencies'
      continueOnError: true

    - bash: |
         python ".azure-pipelines/run_hpu_tests.py"
      displayName: 'HPU Tests in parallel'
      continueOnError: true

    - bash: |
        python -m coverage report
        python -m coverage xml
        python -m coverage html
        python -m codecov --token=$(CODECOV_TOKEN) --commit=$(Build.SourceVersion) --flags=pytest,hpu --name="HPU Test Coverage"
      displayName: 'Statistics'
      continueOnError: true

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'hpu*_test-results.xml'
        testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
      condition: succeededOrFailed()
      displayName: 'Publish test results'
