name: Building docs

on:
  workflow_call:
    inputs:
      actions-ref:
        description: "Version of actions, normally the same as workflow"
        required: false
        type: string
        default: ""
      python-version:
        description: "Python version to use"
        default: "3.9"
        required: false
        type: string
      docs-dir:
        description: "Working directory to run make docs in"
        default: "./docs"
        required: false
        type: string
      timeout-minutes:
        description: "timeout-minutes for each job"
        default: 15
        required: false
        type: number
      requirements-file:
        description: "path to the requirement file"
        default: "requirements/docs.txt"
        required: false
        type: string
      env-vars:
        description: "custom environment variables in json format"
        required: false
        type: string
        default: |
          {
            "SPHINX_MOCK_REQUIREMENTS": 0,
          }
      make-target:
        description: "what test configs to run in json format"
        required: false
        type: string
        default: |
          ["html", "doctest", "linkcheck"]
      install-tex:
        description: "optional installing Texlive support - true|false"
        required: false
        type: string
        default: false

defaults:
  run:
    shell: bash

env:
  # just use CPU version since running on CPU machine
  TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"
  # default 0 means to keep for the maximum time
  KEEP_DAYS: 0

jobs:
  make-docs:
    runs-on: ubuntu-22.04
    env: ${{ fromJSON(inputs.env-vars) }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(inputs.make-target) }}
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ðŸ ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - name: Install pandoc & texlive
        if: ${{ inputs.install-tex == 'true' }}
        timeout-minutes: 10
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y \
            pandoc \
            texlive-latex-extra \
            dvipng \
            texlive-pictures \
            latexmk
      - name: Install dependencies
        timeout-minutes: 20
        run: |
          pip --version
          pip install -e . -U -r ${{ inputs.requirements-file }} -f ${TORCH_URL}
          pip list

      - name: Pull reusable ðŸ¤– actionsï¸
        if: ${{ inputs.actions-ref != '' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.actions-ref }}
          path: .cicd
          repository: Lightning-AI/utilities
      - name: Print ðŸ–¨ï¸ dependencies
        if: ${{ inputs.actions-ref != '' }}
        uses: ./.cicd/.github/actions/pip-list

      - name: Build documentation
        working-directory: ${{ inputs.docs-dir }}
        run: |
          make ${{ matrix.target }} \
            --debug --jobs $(nproc) SPHINXOPTS="-W --keep-going"

      - name: Shorten keep artifact
        if: startsWith(github.event_name, 'pull_request')
        run: echo "KEEP_DAYS=7" >> $GITHUB_ENV
      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ matrix.target }}-${{ github.sha }}
          path: ${{ inputs.docs-dir }}/build/
          retention-days: ${{ env.KEEP_DAYS }}
          include-hidden-files: true
