name: Check Markdown links
# https://github.com/gaurav-nelson/github-action-markdown-link-check

on:
  workflow_call:
    inputs:
      base-branch:
        description: "Default branch name"
        required: true
        type: string
        default: "master"
      config-file:
        description: "Config file (JSON) used for markdown link checks"
        required: false
        type: string
        default: ""
      force-check-all:
        description: "Force check all files, even if not modified (keep empty for default behavior)"
        required: false
        type: string
        default: ""

jobs:
  markdown-link-check:
    runs-on: ubuntu-24.04
    env:
      CONFIG_FILE: ${{ inputs.config-file }}
      MODIFIED_ONLY: "no"
    steps:
      - uses: actions/checkout@master

      - name: Create local version of config
        if: ${{ inputs.config-file == '' }}
        run: |
          echo '{
          "ignorePatterns": [
            {
              "pattern": "^https://github.com/${{ github.repository }}/pull/.*"
            }
          ],
          "httpHeaders": [
            {
              "urls": ["https://github.com/", "https://guides.github.com/", "https://help.github.com/", "https://docs.github.com/"],
              "headers": {
                "Accept-Encoding": "zstd, br, gzip, deflate"
              }
            }
          ]
          }' > 'markdown.links.config.json'
          echo "CONFIG_FILE=markdown.links.config.json" >> $GITHUB_ENV
          cat 'markdown.links.config.json'
      - name: Show config
        run: cat ${{ env.CONFIG_FILE }}

      - name: narrow scope for PR
        if: startsWith(github.event_name, 'pull_request') && inputs.force-check-all == ''
        run: echo "MODIFIED_ONLY=yes" >> $GITHUB_ENV
      - name: Checking markdown link
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: ${{ inputs.base-branch }}
          use-quiet-mode: "yes"
          check-modified-files-only: ${{ env.MODIFIED_ONLY }}
          config-file: ${{ env.CONFIG_FILE }}
