name: Check docs flow

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.9'
        required: false
        type: string
      docs-dir:
        description: 'Working directory to run make docs in'
        default: './docs'
        required: false
        type: string
      timeout-minutes:
        description: 'timeout-minutes for each job'
        default: 15
        required: false
        type: number
      requirements-file:
        description: 'path to the requirement file'
        default: 'requirements/docs.txt'
        required: false
        type: string

jobs:

  docs-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          pip install -e . -U -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install -r ${{ inputs.requirements-file }}
          python --version
          pip --version
          pip list
        shell: bash

      - uses: ./.github/actions/pip-list

      - name: Test Documentation
        working-directory: ${{ inputs.docs-dir }}
        env:
          SPHINX_MOCK_REQUIREMENTS: 0
        run: |
          make doctest
          make coverage

  docs-html:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          pip install -e . -U -r ${{ inputs.requirements-file }} -f https://download.pytorch.org/whl/torch_stable.html
          sudo apt-get update --fix-missing
          sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          python --version
          pip --version
          pip list

      - name: Build documentation
        working-directory: ${{ inputs.docs-dir }}
        run: make html --debug SPHINXOPTS="-W --keep-going"

      - name: Upload built docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-${{ github.sha }}
          path: ${{ inputs.docs-dir }}/build/html/
        if: success()
