name: Check docs flow

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.9'
        required: false
        type: string
      docs-dir:
        description: 'Working directory to run make docs in'
        default: './docs'
        required: false
        type: string
      doctest:
        description: 'test examples inside docs'
        default: true
        required: false
        type: boolean
      timeout-minutes:
        description: 'timeout-minutes for each job'
        default: 15
        required: false
        type: number
      requirements-file:
        description: 'path to the requirement file'
        default: 'requirements/docs.txt'
        required: false
        type: string
      env-vars:
        description: 'custom environment variables in json format'
        required: false
        type: string
        default: |
          {
            "SPHINX_MOCK_REQUIREMENTS": 0,
          }

defaults:
  run:
    shell: bash

env:
  TORCH_URL: "https://download.pytorch.org/whl/torch_stable.html"

jobs:

  docs-test:
    runs-on: ubuntu-20.04
    env: ${{ fromJSON(inputs.env-vars) }}
    if: inputs.doctests != 'false'
    steps:
    - name: Checkout üõé
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python üêç ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        pip install -e . -U -r ${{ inputs.requirements-file }} -f ${TORCH_URL}
        pip --version
        pip list
      shell: bash

    # TODO: re-enable after the external usage is resolved, see #51
    # - uses: ./.github/actions/pip-list

    - name: Test Documentation
      working-directory: ${{ inputs.docs-dir }}
      env:
        SPHINX_MOCK_REQUIREMENTS: 0
      run: |
        make doctest
        make coverage


  docs-html:
    runs-on: ubuntu-20.04
    env: ${{ fromJSON(inputs.env-vars) }}
    steps:
    - name: Checkout üõé
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python üêç ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        pip install -e . -U -r ${{ inputs.requirements-file }} -f ${TORCH_URL}
        sudo apt-get update --fix-missing
        sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
        python --version
        pip --version
        pip list

    - name: Build documentation
      working-directory: ${{ inputs.docs-dir }}
      run: make html --debug SPHINXOPTS="-W --keep-going"

    - name: Upload built docs
      uses: actions/upload-artifact@v3
      with:
        name: docs-${{ github.sha }}
        path: ${{ inputs.docs-dir }}/build/html/
      if: success()
