name: Check formating flow

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.9'
        required: false
        type: string

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        pip install -e '.[test]' --extra-index-url https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install mypy types-setuptools # don't use --upgrade to respect the version installed via setup.py
        pip list

    - uses: ./.github/actions/pip-list
      with:
        unfold: true

    - name: Check typing
      # mypy uses the config file found in the following order:
      # 1. mypy.ini
      # 2. pyproject.toml
      # 3. setup.cfg
      # 4. $XDG_CONFIG_HOME/mypy/config
      # 5. ~/.config/mypy/config
      # 6. ~/.mypy.ini
      # https://mypy.readthedocs.io/en/stable/config_file.html
      run: mypy

  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Determine cache hash
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        # this action also provides an additional behaviour when used in private repositories
        # when configured with a github token, the action will push back fixes to the pull request branch
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
