on:
  push:
    branches: [master, "release/*"]
    paths:
      - ".github/workflows/ci-circleci.yml"
      - ".circleci/config.yml"
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "tests/tests_pytorch/**"
      - "setup.cfg"  # includes pytest config
  pull_request_target:
    branches: [master, "release/*"]
    paths:
      - ".github/workflows/ci-circleci.yml"
      - ".circleci/config.yml"
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "tests/tests_pytorch/**"
      - "setup.cfg"  # includes pytest config

jobs:
  # https://github.com/marketplace/actions/trigger-circleci-pipeline
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          # pass the pull request HEAD sha
          GHA_Meta: ${{ github.event.pull_request.head.sha }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
