name: Test CLI

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

defaults:
  run:
    shell: bash

jobs:
  test-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    timeout-minutes: 10
    steps:
      - name: Checkout üõé
        uses: actions/checkout@v4
      - name: Set up Python üêç ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install package
        run: |
          pip install -e '.[cli]'
          pip list

      - name: run CLI
        working-directory: ./requirements
        run: |
          python -m lightning_utilities.cli version
          python -m lightning_utilities.cli --help
          python -m lightning_utilities.cli requirements set-oldest --req_files="cli.txt"
          python -m lightning_utilities.cli requirements set-oldest --req_files='["cli.txt", "docs.txt"]'

  cli-guardian:
    runs-on: ubuntu-latest
    needs: test-cli
    if: always()
    steps:
      - run: echo "${{ needs.test-cli.result }}"
      - name: failing...
        if: needs.test-cli.result == 'failure'
        run: exit 1
      - name: cancelled or skipped...
        if: contains(fromJSON('["cancelled", "skipped"]'), needs.test-cli.result)
        timeout-minutes: 1
        run: sleep 90
