name: Test App - flagships

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: ["release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - ".github/workflows/ci-flagship-apps.yml"
      - "github/actions/prep-apps/action.yml"
      - "tests/integrations_app/flagship/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test-flagships:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/_flagship-apps.yml
    secrets: inherit
