name: Check Schema

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  check:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@v0.11.2
    with:
      # skip azure due to the wrong schema file by MSFT
      # https://github.com/Lightning-AI/lightning-flash/pull/1455#issuecomment-1244793607
      azure-dir: ""
