name: Test scripts

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

defaults:
  run:
    shell: bash

jobs:
  test-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    timeout-minutes: 15
    steps:
      - name: Checkout üõé
        uses: actions/checkout@v5
      - name: Set up uv and Python üêç ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        timeout-minutes: 5
        run: |
          uv pip install -r requirements/_tests.txt
          uv --version
          uv pip list

      - name: test Scripts
        working-directory: ./scripts
        run: uv run pytest . -v

      - name: Minimize uv cache
        run: uv cache prune --ci

  standalone-run:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 20
    env:
      TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"
      UV_TORCH_BACKEND: cpu
    steps:
      - name: Checkout üõé
        uses: actions/checkout@v5
      - name: Set up uv and Python üêç ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          python-version: "3.10"
          enable-cache: true
      - name: Install dependencies
        timeout-minutes: 20
        run: |
          set -e
          uv pip install -e ".[cli]" -U -r requirements/_tests.txt -f $TORCH_URL
          uv --version
          uv pip list

      - name: Run standalone script
        run: bash ./scripts/run_standalone_tests.sh "tests"
        env:
          COVERAGE_SOURCE: "lightning_utilities"

      - name: Minimize uv cache
        run: uv cache prune --ci

  scripts-guardian:
    runs-on: ubuntu-latest
    needs: [test-scripts, standalone-run]
    if: always()
    steps:
      - run: echo "${{ needs.test-scripts.result }}"
      - name: failing...
        if: needs.test-scripts.result == 'failure'
        run: exit 1
      - name: cancelled or skipped...
        if: contains(fromJSON('["cancelled", "skipped"]'), needs.test-scripts.result)
        timeout-minutes: 1
        run: sleep 90
