name: Test scripts

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

defaults:
  run:
    shell: bash

jobs:
  test-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    timeout-minutes: 15
    steps:
      - name: Checkout üõé
        uses: actions/checkout@v4
      - name: Set up Python üêç ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        timeout-minutes: 5
        run: |
          pip install -r requirements/_tests.txt
          pip --version
          pip list

      - name: test Scripts
        working-directory: ./scripts
        run: pytest . -v

  standalone-run:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 20
    env:
      TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"
    steps:
      - name: Checkout üõé
        uses: actions/checkout@v4
      - name: Set up Python üêç ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        timeout-minutes: 20
        run: |
          set -e
          pip install -e . -U -r requirements/_tests.txt -f $TORCH_URL
          pip --version
          pip list

      - name: Run standalone script
        run: bash ./scripts/run_standalone_tests.sh "tests"
        env:
          COVERAGE_SOURCE: "lightning_utilities"

  scripts-guardian:
    runs-on: ubuntu-latest
    needs: [test-scripts, standalone-run]
    if: always()
    steps:
      - run: echo "${{ needs.test-scripts.result }}"
      - name: failing...
        if: needs.test-scripts.result == 'failure'
        run: exit 1
      - name: cancelled or skipped...
        if: contains(fromJSON('["cancelled", "skipped"]'), needs.test-scripts.result)
        timeout-minutes: 1
        run: sleep 90
