name: Test App

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]  # added `ready_for_review` since draft is skipped
    paths:
      - ".actions/**"
      - ".github/workflows/ci-tests-app.yml"
      - "src/lightning_app/**"
      - "tests/tests_app/**"
      - "requirements/app/**"
      - "setup.py"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

defaults:
  run:
    shell: bash

jobs:
  app-pytest:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-11, windows-2022]
        pkg-name: ["app"]
        python-version: ["3.8"]
        requires: ["oldest", "latest"]
        include:
          # "lightning" installs the monolithic package
          - {os: "macOS-11", pkg-name: "lightning", python-version: "3.9", requires: "latest"}
          - {os: "ubuntu-20.04", pkg-name: "lightning", python-version: "3.9", requires: "latest"}
          - {os: "windows-2022", pkg-name: "lightning", python-version: "3.8", requires: "latest"}
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 45
    env:
      PACKAGE_NAME: ${{ matrix.pkg-name }}
      FREEZE_REQUIREMENTS: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: basic setup
        run: pip install -q -r .actions/requirements.txt

      - name: Set min. dependencies
        if: ${{ matrix.requires == 'oldest' }}
        run: python .actions/assistant.py replace_oldest_ver

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ matrix.pkg-name }}-${{ matrix.requires }}-${{ hashFiles('requirements/app/base.txt') }}
          restore-keys: pip-${{ matrix.pkg-name }}-
          enableCrossOsArchive: true

      - name: Switch PyTorch URL
        run: python -c "print('TORCH_URL=https://download.pytorch.org/whl/' + str('test/cpu/torch_test.html' if '${{matrix.release}}' == 'pre' else 'cpu/torch_stable.html'))" >> $GITHUB_ENV

      - name: Install package & dependencies
        run: |
          python -m pip install -q pip -U
          pip install -e .[dev] --upgrade --find-links ${TORCH_URL}
          pip list

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Adjust tests
        if: ${{ matrix.pkg-name == 'lightning' }}
        run: |
          python .actions/assistant.py copy_replace_imports --source_dir="./tests" \
            --source_import="lightning_app,lightning_fabric,pytorch_lightning" \
            --target_import="lightning.app,lightning.fabric,lightning.pytorch"

      - name: Adjust examples
        if: ${{ matrix.pkg-name != 'lightning' }}
        run: |
          python .actions/assistant.py copy_replace_imports --source_dir="./examples" \
            --source_import="lightning.app,lightning" \
            --target_import="lightning_app,lightning_app"

      - name: Switch coverage scope
        run: python -c "print('COVERAGE_SCOPE=' + str('lightning' if '${{matrix.pkg-name}}' == 'lightning' else 'lightning_app'))" >> $GITHUB_ENV

      - name: Tests
        working-directory: ./tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          python -m coverage run --source ${{ env.COVERAGE_SCOPE }} \
            -m pytest -m "not cloud" tests_app \
            --timeout=300 -vvvv --durations=50

      - name: Statistics
        if: success()
        working-directory: ./tests
        run: |
          coverage xml -i
          coverage report -i

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/coverage.xml
          flags: ${{ env.COVERAGE_SCOPE }},cpu,pytest
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
