name: Apply checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-typing:
    uses: ./.github/workflows/check-typing.yml
    with:
      actions-ref: ${{ github.sha }} # use local version
      extra-typing: "typing"

  check-precommit:
    uses: ./.github/workflows/check-precommit.yml

  check-schema-latest:
    uses: ./.github/workflows/check-schema.yml
    with:
      azure-dir: ""

  check-schema-fixed:
    uses: ./.github/workflows/check-schema.yml
    with:
      actions-ref: ${{ github.sha }} # use local version
      azure-dir: ""

  check-schema:
    runs-on: ubuntu-latest
    # just aggregation of the previous two jobs
    needs: ["check-schema-latest", "check-schema-fixed"]
    steps:
      - run: echo "done"

  check-package:
    uses: ./.github/workflows/check-package.yml
    with:
      actions-ref: ${{ github.sha }} # use local version
      artifact-name: dist-packages-${{ github.sha }}
      import-name: "lightning_utilities"
      build-matrix: |
        {
          "os": ["ubuntu-22.04"],
          "python-version": ["3.10"]
        }
      testing-matrix: |
        {
          "os": ["ubuntu-22.04", "macos-13", "windows-2022"],
          "python-version": ["3.8", "3.12"]
        }

  check-package-extras:
    uses: ./.github/workflows/check-package.yml
    with:
      actions-ref: ${{ github.sha }} # use local version
      artifact-name: dist-packages-${{ github.sha }}
      import-name: "lightning_utilities"
      install-extras: "[cli]"
      # todo: when we have a module with depence on extra, replace it
      #  tried to import `lightning_utilities.cli.__main__` but told me it does not exits
      custom-import: "import fire"
      testing-matrix: |
        {
          "os": ["ubuntu-22.04", "macos-13", "windows-2022"],
          "python-version": ["3.10"]
        }

  check-docs:
    uses: ./.github/workflows/check-docs.yml
    with:
      requirements-file: "requirements/_docs.txt"
      install-tex: true

  check-md-links-default:
    uses: ./.github/workflows/check-md-links.yml
    with:
      base-branch: main

  check-md-links-w-config:
    uses: ./.github/workflows/check-md-links.yml
    with:
      base-branch: main
      config-file: ".github/markdown.links.config.json"
