name: CI build Docker
# https://www.docker.com/blog/first-docker-github-action-is-here
# https://github.com/docker/build-push-action
# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-Conda:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.7, 3.8]
        pytorch_version: [1.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        # publish master
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: dockers/conda/Dockerfile
          build_args: PYTHON_VERSION=${{ matrix.python_version }},PYTORCH_VERSION=${{ matrix.pytorch_version }}
          push: false
        timeout-minutes: 40

  build-XLA:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.7]
        xla_version: [1.6, "nightly"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        # publish master
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: dockers/base-xla/Dockerfile
          build_args: PYTHON_VERSION=${{ matrix.python_version }},XLA_VERSION=${{ matrix.xla_version }}
          push: false
        timeout-minutes: 40

  build-cuda:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python_version: 3.7
            pytorch_version: 1.7
            pytorch_channel: pytorch-nightly
          - python_version: 3.8
            pytorch_version: 1.5
            pytorch_channel: pytorch
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        # publish master
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: dockers/base-cuda/Dockerfile
          build_args: PYTHON_VERSION=${{ matrix.python_version }},PYTORCH_VERSION=${{ matrix.pytorch_version }},PYTORCH_CHANNEL=${{ matrix.pytorch_channel }}
          push: false
        timeout-minutes: 40
