name: CI complete testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]

jobs:

  pytest:

    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macOS-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9]
        requires: ['minimal', 'latest']
        exclude:
          - python-version: 3.9
            requires: 'minimal'

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    # TODO: the macOS is taking too long, probably caching did not work...
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        # todo: unfreeze PIP after resolving minimal dependencies
        pip install --quiet "pip==20.1" --upgrade --user  # needed for get pip cacher folder

    # Github Actions: Run step on specific OS: https://stackoverflow.com/a/57948488/4521646
    - name: Setup macOS
      if: runner.os == 'macOS'
      run: |
        brew install libomp  # https://github.com/pytorch/pytorch/issues/20030
        brew install openmpi libuv  # Horovod on macOS requires OpenMPI, Gloo not currently supported

    - name: Setup Windows
      if: runner.os == 'windows'
      run: |
        # remove Horovod from requirements
        fname = 'requirements/extra.txt'
        lines = [line for line in open(fname).readlines() if not line.startswith('horovod')]
        open(fname, 'w').writelines(lines)
      shell: python

    # todo: re-enable when allow testing py 3.9 with min config, atm some Hydra issues
    #- name: Adjust minimal for Python 3.9
    #  if: matrix.requires == 'minimal' && matrix.python-version == 3.9
    #  run: |
    #    import re
    #    def _req(fname, ptn, ver):
    #        req = re.sub(ptn, ver, open(fname).read())
    #        open(fname, 'w').write(req)
    #
    #    _req('requirements.txt', r'torch>=[\d\.]+', 'torch>=1.8.0')
    #    _req('requirements/extra.txt', r'onnxruntime>=[\d\.]+', 'onnxruntime>=1.7.0')
    #  shell: python

    - name: Set min. dependencies
      if: matrix.requires == 'minimal'
      run: |
        files = (
            'requirements.txt',
            'requirements/extra.txt',
            'requirements/loggers.txt',
            'requirements/test.txt',
            'requirements/examples.txt',
        )
        for fname in files:
            req = open(fname).read().replace('>=', '==')
            open(fname, 'w').write(req)

        # remove Fairscale from requirements
        fname = 'requirements/extra.txt'
        lines = [line for line in open(fname).readlines() if 'fairscale' not in line]
        open(fname, 'w').writelines(lines)
      shell: python

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ matrix.requires }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements/extra.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ matrix.requires }}-

    - name: Pull checkpoints from S3
      run: |
        cd legacy
        # wget is simpler but does not work on Windows
        python -c "from urllib.request import urlretrieve ; urlretrieve('https://pl-public-data.s3.amazonaws.com/legacy/checkpoints.zip', 'checkpoints.zip')"
        ls -l .
        unzip -o checkpoints.zip
        ls -l checkpoints/

    # todo: re-enable testing with Horovod
    - name: py3.9 - temp skip Horovod
      if: matrix.python-version == 3.9
      run: |
        # pip uninstall -y horovod
        python -c "fname = 'requirements/extra.txt' ; lines = [line for line in open(fname).readlines() if not line.startswith('horovod')] ; open(fname, 'w').writelines(lines)"

    - name: Install dependencies
      env:
        # MAKEFLAGS: "-j2"
        HOROVOD_BUILD_ARCH_FLAGS: "-mfma"
        HOROVOD_WITHOUT_MXNET: 1
        HOROVOD_WITHOUT_TENSORFLOW: 1
      run: |
        python --version
        pip --version
        # python -m pip install --upgrade --user pip
        pip install --requirement requirements.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html --upgrade
        # adjust versions according installed Torch version
        python ./requirements/adjust_versions.py requirements/extra.txt
        python ./requirements/adjust_versions.py requirements/examples.txt
        pip install --requirement ./requirements/devel.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html --upgrade
        pip list
      shell: bash

    - name: Reinstall Horovod if necessary
      # todo: re-enable horovod on py3.9 when it will be supported
      if: runner.os != 'windows' && matrix.python-version != 3.9
      env:
        HOROVOD_BUILD_ARCH_FLAGS: "-mfma"
      run: |
        HOROVOD_BUILT=$(python -c "import horovod.torch; horovod.torch.nccl_built(); print('SUCCESS')" || true)
        if [[ $HOROVOD_BUILT != "SUCCESS" ]]; then
          pip uninstall -y horovod
          echo $(grep "horovod" requirements/extra.txt) > requirements/horovod.txt
          pip install --no-cache-dir -r requirements/horovod.txt
        fi
        horovodrun --check-build
      shell: bash

    - name: Cache datasets
      uses: actions/cache@v2
      with:
        path: Datasets
        key: pl-dataset

    - name: Tests
      run: |
        # NOTE: do not include coverage report here, see: https://github.com/nedbat/coveragepy/issues/1003
        coverage run --source pytorch_lightning -m pytest pytorch_lightning tests -v --durations=50 --junitxml=junit/test-results-${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.requires }}.xml

    - name: Examples
      run: |
        python -m pytest pl_examples -v --durations=10

    - name: Upload pytest results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.requires }}
        path: junit/test-results-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.requires }}.xml
      if: failure()

    - name: Statistics
      if: success()
      run: |
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: always()
      # see: https://github.com/actions/toolkit/issues/399
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: cpu,pytest,python${{ matrix.python-version }}
        name: CPU-coverage
        fail_ci_if_error: false
