name: "Check Formatting"
on: [push, pull_request]

jobs:
  check_code_formatting:
    name: Check code formatting with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install black==19.10b0
      - name: Run Black
        run: black --skip-string-normalization --config=pyproject.toml --check . # TODO, uncomment
