name: "Deploy Docs"
on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  # https://github.com/marketplace/actions/deploy-to-github-pages
  build-docs-deploy:
    runs-on: ubuntu-20.04
    env:
      TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4
        # If you're using actions/checkout@v4 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          submodules: recursive
      - name: Set up Python üêç
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Note: This uses an internal pip API and may not always work
      # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
      - name: Cache üíΩ pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: pip-

      - name: Install texlive
        timeout-minutes: 20
        run: |
          # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
          sudo apt-get update --fix-missing
          sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
        shell: bash

      - name: Install dependencies
        timeout-minutes: 20
        run: |
          pip --version
          pip install -e . -U -q -r requirements/_docs.txt -f ${TORCH_URL}
          pip list
        shell: bash

      - name: Make Documentation
        working-directory: ./docs
        run: make html --jobs 2

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # If you'd like to push the contents of the deployment folder into a specific directory
          single-commit: true # you'd prefer to have a single commit on the deployment branch instead of full history
        if: success()
