name: "Deploy Docs"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  # https://github.com/marketplace/actions/deploy-to-github-pages
  build-docs-deploy:
    runs-on: ubuntu-latest
    env:
      TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"
      UV_TORCH_BACKEND: cpu
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v6
        # If you're using actions/checkout@v6 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          submodules: recursive
      - name: Set up uv and Python üêç
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          python-version: "3.10"
          enable-cache: true

      #- name: Install texlive
      #  timeout-minutes: 20
      #  run: |
      #    # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
      #    sudo apt-get update --fix-missing
      #    sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
      #  shell: bash

      - name: Install dependencies
        timeout-minutes: 20
        run: |
          uv --version
          uv pip install -e . -U -q -r requirements/_docs.txt -f ${TORCH_URL}
          uv pip list
        shell: bash

      - name: Make Documentation
        working-directory: ./docs
        run: make html --jobs 2

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.7.6
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # If you'd like to push the contents of the deployment folder into a specific directory
          single-commit: true # you'd prefer to have a single commit on the deployment branch instead of full history

      - name: Minimize uv cache
        run: uv cache prune --ci
