name: Create Legacy Ckpts

on:
  workflow_dispatch:
    inputs:
      push_to_s3:
        description: 'Push generated checkpoints to S3'
        required: false
        type: boolean

jobs:
  create-legacy-ckpts:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./legacy
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        # Python version here needs to be supported by all PL versions listed in back-compatible-versions.txt.
        python-version: 3.8

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-1

    - name: Generate checkpoints
      run: |
        bash generate_checkpoints.sh $(cat back-compatible-versions.txt)

    - name: Upload checkpoints as GitHub Actions' artifact
      uses: actions/upload-artifact@v3
      with:
        name: checkpoints-${{ github.sha }}
        path: legacy/checkpoints/
      if: always()

    - name: Upload checkpoints to S3
      run: |
        aws s3 sync --dryrun checkpoints/ s3://pl-public-data/legacy/checkpoints/
        zip -r checkpoints.zip checkpoints
        aws s3 cp --dryrun checkpoints.zip s3://pl-public-data/legacy/ --acl public-read
      if: ${{ github.event.inputs.push_to_s3 == 'true' }}
