name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [main, "release/*"]
    tags: ['v?[0-9]+.[0-9]+.[0-9]+']
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:

  # based on https://github.com/pypa/gh-action-pypi-publish
  build-package:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
    - name: Set up Python ğŸ
      uses: actions/setup-python@v4
      with:
          python-version: 3.8

    - name: Create package ğŸ“¦
      uses: ./.github/actions/pkg-create
    - name: Upload ğŸ“¤ to the share store
      if: ${{ inputs.artifact-name != '' }}
      uses: actions/upload-artifact@v3
      with:
        name: pypi-packages-${{ github.sha }}
        path: dist


  upload-package:
    needs: build-package
    if: github.event_name == 'release'
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
    - name: Download ğŸ“¥ artifact
      uses: actions/download-artifact@v3
      with:
        name: pypi-packages-${{ github.sha }}
        path: dist
    - name: local ğŸ—ƒï¸ files
      run: ls -lh dist/

    - name: Upload to release
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'dist/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}


  delay-publish:
    needs: build-package
    runs-on: ubuntu-20.04
    steps:
    - name: Delay â° releasing
      uses: juliangruber/sleep-action@v1
      with:
        time: 5m


  publish-package:
    needs: delay-publish
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
    - name: Download ğŸ“¥ artifact
      uses: actions/download-artifact@v3
      with:
        name: pypi-packages-${{ github.sha }}
        path: dist
    - name: local ğŸ—ƒï¸ files
      run: ls -lh dist/

    # We do this, since failures on test.pypi aren't that bad
    - name: Publish to Test PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true

    - name: Publish distribution ğŸ“¦ to PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
