name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [main, "release/*"]
    tags: ["v?[0-9]+.[0-9]+.[0-9]+"]
  release:
    types: [published]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  # based on https://github.com/pypa/gh-action-pypi-publish
  build-package:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Set up Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Prepare build env.
        run: pip install -r ./requirements/gha-package.txt
      - name: Create ğŸ“¦ package
        uses: ./.github/actions/pkg-create
      - name: Upload ğŸ“¤ packages
        uses: actions/upload-artifact@v4
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist

  upload-package:
    needs: build-package
    if: github.event_name == 'release'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Download ğŸ“¥ artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist
      - name: local ğŸ—ƒï¸ files
        run: ls -lh dist/

      - name: Upload to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "dist/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  publish-package:
    needs: build-package
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download ğŸ“¥ artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist
      - name: local ğŸ—ƒï¸ files
        run: ls -lh dist/

      # We do this, since failures on test.pypi aren't that bad
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publish distribution ğŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
