name: Clear cache weekly

on:
  schedule:
    # on Sundays
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      pattern:
        description: 'patter for cleaning cache'
        default: "pip-|conda"
        required: false
        type: string

jobs:

  cron-clear:
    if: github.event_name == 'schedule'
    uses: Lightning-AI/utilities/.github/workflows/clear-cache.yml@v0.7.1
    with:
      pattern: 'latest|docs'

  direct-clear:
    if: github.event_name == 'workflow_dispatch'
    uses: Lightning-AI/utilities/.github/workflows/clear-cache.yml@v0.7.1
    with:
      pattern: ${{ inputs.pattern }}
